# Generated by Django 4.1 on 2023-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_alter_choice_notes_alter_choice_second_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='second_answer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
