# Generated by Django 4.1 on 2023-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='IDENTITY',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
