# Generated by Django 4.1 on 2023-09-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_patient_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.patient'),
        ),
    ]
